version: "2"
## exclude test files from code quality report
exclude_patterns:
  - "**/*.test.js"
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 60
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
