image: node:latest

stages:
  - test
  - coverage
  - build

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - npm run test

coverage:
  stage: coverage
  script:
    - npm run coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
      junit: junit.xml

build:
  stage: build
  script:
    - npm run build
