image: node:latest

stages:
  - prepare
  - build
  - test

cache:
  paths:
    - node_modules/

include:
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

variables:
  SAST_DISABLE_DIND: "true"

prepare:
  stage: prepare
  script:
    - npm install --progress=false

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 7 days
    paths:
      - build/
  needs: ["prepare"]

sast:
  stage: test
  needs: []

test:
  stage: test
  script:
    - CI=true npm run test
  artifacts:
    reports:
      junit:
        - ./junit.xml
  needs: ["prepare"]

coverage:
  stage: test
  script:
    - CI=true npm run coverage
  artifacts:
    reports:
      cobertura:
        - ./coverage/cobertura-coverage.xml
  needs: ["prepare"]
