image: node:latest

stages:
  - test
  - coverage
  - build

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - CI=true npm run test
  artifacts:
    reports:
      junit:
        - ./junit.xml

coverage:
  stage: coverage
  script:
    - CI=true npm run coverage
  artifacts:
    reports:
      cobertura:
        - ./coverage/cobertura-coverage.xml

build:
  stage: build
  script:
    - npm run build
