image: node:latest

stages:
  - prepare
  - build
  - test

cache:
  paths:
    - node_modules/

prepare:
  stage: prepare
  script:
    - npm install --progress=false

build:
  stage: build
  script:
    - npm run build
  artifacts:
    expire_in: 7 days
    paths:
      - build/

test:
  stage: test
  script:
    - CI=true npm run test
  artifacts:
    reports:
      junit:
        - ./junit.xml

coverage:
  stage: test
  script:
    - CI=true npm run coverage
  artifacts:
    reports:
      cobertura:
        - ./coverage/cobertura-coverage.xml
