#!/bin/bash
ln -s /etc/nginx/sites-available/OpenMediaCenter.conf /etc/nginx/sites-enabled/OpenMediaCenter.conf

ln -s /var/run/php/php*-fpm.sock /var/run/php-fpm.sock

mysql -uroot -pPASS -e "CREATE DATABASE mediacenter;"
mysql -uroot -pPASS -e "CREATE USER 'mediacenteruser'@'localhost' IDENTIFIED BY 'mediapassword';"
mysql -uroot -pPASS -e "GRANT ALL PRIVILEGES ON mediacenter . * TO 'mediacenteruser'@'localhost';"
mysql -u mediacenteruser -pmediapassword mediacenter < /tmp/openmediacenter.sql

rm /tmp/openmediacenter.sql

systemctl restart nginx
